### ISSUE TITLE
Bug - TARIFFS - Delete tariff - currently also works with used tariffs

### ISSUE THREAD

**Issue by andihame** [eegfaktura/eegfaktura-web#4]
If a tariff is deleted that is allocated to a metering point or member, the tariff and also the allocation disappear. This should not be.

In addition, a warning should also appear

**Comment by LucaGeissler** [comment]
Tariffs in use should ALWAYS be replaced with another Tarif if they want to be removed

**Comment by LucaGeissler** [comment]
show toast to tell the user a certain tariff is still in use when they want to remove it
